Ml searcher add pretrained
gsvgit/VSharp pull request #76
Opened 2023-11-03 16:32 UTC by katyacyfra

2023-11-05 14:21 UTC, emnigma commented
@katyacyfra , Замечаешь, что у тебя не проходит CI? красный крест и написано "Al checks have failed". У нас только один чек, это проверка на кодстайл, чтобы код был однообразный и его было легче читать

Тебе надо при активном питоновском окружении прописать 
```
pip install pre-commit
pre-commit install
```
Тогда после написания тобой команды "commit" инструмент проверит код и поправит его. После этого поправленный код снова нужно добавить в индекс командой `git add` и снова прописать `git commit`

2023-11-07 08:55 UTC, emnigma requested changes

2023-11-07 08:55 UTC, emnigma commented on VSharp.ML.AIAgent/ml/data_loader_compact.py
> +        data['game_vertex', 'to', 'game_vertex'].edge_attr = torch.tensor(np.array(edges_attr_v_v), dtype=torch.long)
вроде как хотели из таплов строки сделать?

2023-11-07 08:55 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/EdgeTypeRGCNSageSubgraphs64ch/model.py
> +    def __init__(self, hidden_channels, out_channels):
я знаю, что можно сделать без енкодеров, [вот так например Аня делала](https://github.com/Anya497/VSharp/blob/16361a69fc36981035195a6c28d385e45ec636ae/VSharp.ML.AIAgent/ml/models.py#L809).

или z-dict тебе очень нужен?

2023-11-07 08:55 UTC, emnigma commented on VSharp.ML.AIAgent/predict_state_hetero.py
> +    def predict_state(model, data: HeteroData, state_map: Dict[int, int]) -> int:
обязательно ли функция должна статически принадлежать классу?

2023-11-07 08:55 UTC, emnigma commented on VSharp.ML.AIAgent/predict_state_hetero.py
> +        out = model(data.x_dict, data.edge_index_dict)
у нас вроде уже 8 входов. этот код все еще актуален?

2023-11-07 08:55 UTC, emnigma commented on VSharp.ML.AIAgent/predict_state_hetero.py
> +if __name__ == "__main__":
в файлах, которые не используются как исполняемые, то есть те, в которых только функции лежат, лучше не писать `if__name__ == "__main__":`, иначе у читающего создается впечатление, что это исполняемый файл

2023-11-07 09:00 UTC, katyacyfra commented on VSharp.ML.AIAgent/ml/models/EdgeTypeRGCNSageSubgraphs64ch/model.py
> +    def __init__(self, hidden_channels, out_channels):
Можно и без них, вопрос в том, что нужно? Какой формат?

2023-11-07 09:01 UTC, katyacyfra commented on VSharp.ML.AIAgent/ml/data_loader_compact.py
> +        data['game_vertex', 'to', 'game_vertex'].edge_attr = torch.tensor(np.array(edges_attr_v_v), dtype=torch.long)
Через пробел пойдет? Поправлю

2023-11-07 09:27 UTC, emnigma commented on VSharp.ML.AIAgent/ml/data_loader_compact.py
> +        data['game_vertex', 'to', 'game_vertex'].edge_attr = torch.tensor(np.array(edges_attr_v_v), dtype=torch.long)
лучше через нижние подчеркивания

2023-11-07 10:48 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/EdgeTypeRGCNSageSubgraphs64ch/model.py
> +    def __init__(self, hidden_channels, out_channels):
на вход форварда 8 параметров (сейчас ты добавила восьмой, поэтому 8, по ссылке 7), на выход - результат работы модели. Отдельную обертку (Encoder) делать не надо, z_dict делать не надо

2023-11-09 09:48 UTC, emnigma requested changes

2023-11-09 09:48 UTC, emnigma commented on VSharp.ML.AIAgent/ml/predict_state_vector_hetero.py
>          out = model(data.x_dict, data.edge_index_dict)
тут все еще старый предикт?

2023-11-09 09:48 UTC, emnigma commented on VSharp.ML.AIAgent/ml/data_loader_compact.py
> +        data["game_vertex_to_game_vertex"].edge_attr = torch.tensor(
тут если edges_attr_v_v, edges_types_v_v могут быть пустыми, то нужно соответствующие тензоры оборачивать в null_if_empty. но это ладно, сделаю сам

2023-11-21 13:12 UTC, merged