Batching in common model training
gsvgit/VSharp pull request #79
Opened 2023-11-23 15:32 UTC by Anya497

- Refactor dataset creating
- Remove dict support in model's output 
- Add directory with code for teachers 
- Add simple random autotuner

2023-11-23 16:29 UTC, emnigma requested changes

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/learning/play_game.py
> +# from ray.experimental.tqdm_ray import tqdm
лишний коммент

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +                step.use_for_train = True
вот эту лестницу никак нельзя проще сделать? выглядит как много общих случаев

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +
тут как будто две операции: filter и потом map. если хочешь, можешь сделать красивей

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +            self.maps_data[map_name] = (map_result, filtered_map_steps)
почему тут в одном случае есть логгирование, а в другом - нет?

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/models.py
> +        z_dict["game_vertex"] = x_dict["game_vertex"]
откуда z_dict? мы вроде решили без него

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/models.py
>                  edge_index_dict[("state_vertex", "parent_of", "state_vertex")],
старый код: сейчас доступ не через кортеж, а через строку

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/paths.py
> +dataset_map_results_file_name = os.path.join("report", "dataset_state.csv")
круто, что в отдельном файле

константы лучше писать капсом

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
в 48 строчке файла вижу `with open(path_to_csv, "r") as csv_file:`, который кончается, выход из контекстного менеджера не происходит до конца функции. хотя сам контекстный менеджер (открытый файл) тебе нужен.

строчки с 61 по 80 можно сдвинуть влево на один уровень индексации бесплатно. чем меньше табов, тем лучше код читается

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
>                  best_model_score = best_model[1]
называется "variable unpacking"
```suggestion
                best_model_name, best_model_score = best_model[0], best_model[1]
```

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +                best_models[map_name] = [
ты собираешься менять содержимое best_models[map_name]? лучше tuple, он неизменяемый, труднее допустить ошибку

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +                best_models[row[0]][1] = ast.literal_eval(row[2])
а, вижу. лучше переписывать значения
```suggestion
                best_models[row[0]] = (ref_model, ast.literal_eval(row[2]), row[1])
```

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    weights["lin_last.bias"] = torch.tensor(np.random.random([1]))
почему bias рандомный? его в слое Linear можно сделать отсутствующим

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/wrapper.py
> -        back_prop(
а куда делось?

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/TAGSageSimple/model_modified.py
> +from learning.timer.wrapper import timeit
timeit откуда?

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/TAGSageSimple/model_modified.py
> +from torch_geometric.nn import Linear
вот тут два Linear. какой из них нужный? используется, насколько я знаю, только последний

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/TAGSageTeacher/model.py
откуда взялся TagSageTeacher? мы же решили, что создадим папку 'teachers' в папке с архитектурой?

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/TAGSageTeacher/model_modified.py
откуда взялся state_encoder? почему модель называется StateGNNEncoderConvEdgeAttr, а название папки, которая вроде как архитектура, TAGSageTeacher?

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        all_maps = get_maps(websocket=ws, type=MapsType.TRAIN)
карты нужны только если generate_dataset=True, нужно переместить под условие

2023-11-23 16:29 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        generate_dataset = False
это надо убрать, тем более, что для простых типов при попытке использовать переданное значение меняется копия этого значения и с переданным ничего не происходит

2023-11-24 09:42 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +            self.maps_data[map_name] = (map_result, filtered_map_steps)
Потому что оно нужно только в том случае, где оно есть. Другой используется для создания датасета. Там логирование не нужно.

2023-11-24 09:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/models.py
> +        z_dict["game_vertex"] = x_dict["game_vertex"]
Да. Я просто забыла про этот файл :)

2023-11-24 09:52 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/models/TAGSageTeacher/model.py
Так там и есть архитектура учителей. Просто без весов. Я могу создать там папку "teachers" и добавить все веса.

2023-11-24 09:57 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/models/TAGSageTeacher/model_modified.py
Старые веса со state_encoder. Поэтому его, видимо, нужно оставить для этой модели.

2023-11-30 22:03 UTC, emnigma requested changes
Я пару вещей не понял, на пару вещей не ответила, запросил изменения еще раз

Обычно при ревью отвечают на все комментарии, так я буду знать, на что ты обратила внимание, а что нет. Можно даже ставить 
- [ ]  вот такие галочки

и ими отмечать то, что ты сделала

+ еще просьба: пожалуйста сначала влей мои изменения, потом делай коммит, иначе мне снова придется решать конфликты

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +            self.maps_data[map_name] = (map_result, filtered_map_steps)
мне не нравится, но ок

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    weights["lin_last.bias"] = torch.tensor(np.random.random([1]))
тык (это про прошлый коммент: lin_last можно убрать, выставив в Linear атрибут bias=False)

разобрались

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +        return best_models
вот этот return заканчивается когда заканчивается первая эпоха, а цикл `48: for epoch_num in range(1, len(os.listdir(csv_path)) + 1):` еще не истощился, почему так? посмотри пожалуйста

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    np.random.seed(random_seed)
почему в этой функции, а не глобально? подразумевается, что она будет вызываться несколько раз, и/или сид должен быть разный для всей программы? если это не так, то надо установить np.random.seed один раз в начале функции main()

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +import numpy as np
зачем второй раз импортировать numpy? найди пожалуйста оптимизатор импортов

тут я пока ребейзил поковырялся, импорты поправил, забей

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +    multiprocessing.set_start_method("spawn", force=True)
force зачем?

2023-11-30 22:03 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        all_results = sorted(all_results, key=lambda x: x.map.MapName)
есть in-place метод сортировки, просто `list_of_things.sort(key=...)`, это работает быстрее

2023-11-30 22:05 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +
забила?

2023-11-30 22:05 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +                step.use_for_train = True
забила?

2023-11-30 22:07 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/models.py
> +        z_dict["game_vertex"] = x_dict["game_vertex"]
Поправила?

2023-11-30 22:08 UTC, emnigma commented on VSharp.ML.AIAgent/ml/models/TAGSageTeacher/model.py
не надо, сделали по другому, в моем пр-е пример использования

2023-11-30 22:10 UTC, emnigma commented on VSharp.ML.AIAgent/learning/play_game.py
> +# from ray.experimental.tqdm_ray import tqdm
тык

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    weights["lin_last.bias"] = torch.tensor(np.random.random([1]))
Так пусть тоже учится

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/wrapper.py
> -        back_prop(
стало не нужно. Это wrapper для генерации датасета, а не для обучения

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +            self.maps_data[map_name] = (map_result, filtered_map_steps)
ну оно так должно работать. Что не нравится?

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +                step.use_for_train = True
нет. Там сильно красиво не получается, но немножко сократить удалось

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/dataset.py
> +
я попробовала, с filter и map код выглядит страшно и непонятно. Так лучше

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/models.py
> +        z_dict["game_vertex"] = x_dict["game_vertex"]
да

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    weights["lin_last.bias"] = torch.tensor(np.random.random([1]))
иногда я учу отдельно последний слой. Пока хочу обучать с bias

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +                best_models[map_name] = [
Изменила на tuple

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +                best_models[row[0]][1] = ast.literal_eval(row[2])
поправила

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/models/TAGSageSimple/model_modified.py
> +from learning.timer.wrapper import timeit
убрала, он не нужен

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/learning/play_game.py
> +# from ray.experimental.tqdm_ray import tqdm
убрала

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        generate_dataset = False
убрала

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    np.random.seed(random_seed)
идея в том, что у моделек должен быть одинаковый сид, чтобы результат был более предсказуемым. Не обязательно во всей программе так делать. Поэтому только здесь

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/run_common_model_training.py
> +    multiprocessing.set_start_method("spawn", force=True)
по-моему, без него не работало

2023-12-05 08:44 UTC, Anya497 commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        all_results = sorted(all_results, key=lambda x: x.map.MapName)
Хорошо. Это можно со следующим pr-ом докинуть?

2023-12-05 08:45 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +        all_results = sorted(all_results, key=lambda x: x.map.MapName)
да

2023-12-05 08:45 UTC, emnigma commented on VSharp.ML.AIAgent/run_common_model_training.py
> +    multiprocessing.set_start_method("spawn", force=True)
ладно.

2023-12-05 08:48 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +    np.random.seed(random_seed)
изменение сида глобальное. давай отдельным пр-ом

2023-12-05 08:54 UTC, emnigma commented on VSharp.ML.AIAgent/ml/common_model/utils.py
> +        return best_models
надо пофиксить

- [ ] пофиксить

2023-12-05 09:26 UTC, merged